# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: true

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru если сборка упала
notifications:
  email:
    recipients:
      - envereskendarov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

services:
  - postgresql

before_install:
  - psql -c 'create database testdb;' -U postgres

env:
  global:
    - CODECOV_TOKEN='0eb2c9a1-a8bf-4710-a82a-f89e7c374451'
